# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Monthly geobtaa report
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 * *

jobs:
  create_issue:
    name: Monthly geobtaa report
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Today's date
        run: echo "TODAY=$(date '+%Y-%B')" >> $GITHUB_ENV
    
      - name: Create issue
        uses: imjohnbo/issue-bot@3d96848fb5e9a4a473bb81ae62b4b4866a56e93a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          assignees: "karenmajewicz"
          labels: "reports"
          title: ${{ env.TODAY }} geobtaa Monthly Report
          project: 4
          body: |
            ### To do
          pinned: true
          close-previous: false
